{
 "title": "IBM Event Streams Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "rn", "label": "Release", "query": "label_values(release)" },
   {
    "name": "kafka",
    "label": "kafka",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate_value{kubernetes_namespace=~\"$ns\"},  kafka)"
   }
  ]
 },
 "panels": [
  { "title": "Event Streams Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eventstreams Pod Status",
   "type": "graph",
   "description": "The status of the Event Streams pods, all should be in the running state with no unready pods ideally. Pods may become unready for short periods of time if they are busy, but if this happens often there may be a bottlenecking issue",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Pod Count" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$ns\", pod=~\"$rn-.*\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$ns\", pod=~\"$rn-.*\", condition=\"false\"})",
     "legendFormat": "Unready"
    }
   ]
  },
  {
   "title": "ICP Pod Status",
   "type": "graph",
   "description": "The status of the ICP pods, all should be in the running state with no unready pods ideally. Pods may become unready for short periods of time if they are busy, but if this happens often there may be a bottlenecking issue",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Pod Count" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kube-system\", pod=~\".*\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"kube-system\", pod=~\".*\", condition=\"false\"})",
     "legendFormat": "Unready"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "UnderReplicatedPartitions: In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "description": "ActiveControllerCount: The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  {
   "title": "Topics & Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offline partition count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Parition Count" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
      }
     ]
    },
    {
     "title": "Under min ISR",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Partition Count" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
      }
     ]
    },
    {
     "title": "Under replicated partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Parition Count" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Byte rate into kafka",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$ns\", release=\"$rn\"}",
     "legendFormat": "Kafka-{{ kafka }}"
    }
   ]
  },
  {
   "title": "Byte rate out of kafka",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$ns\", release=\"$rn\"}",
     "legendFormat": "Kafka-{{ kafka }}"
    }
   ]
  }
 ]
}